services:
  dbndg:
    image: dbndg:build
    build: https://github.com/jtagcat/docker-build-nodot-git.git#main
    environment:
      - DESTINATION_BASE=https://git.sr.ht
    expose:
      - 8080
    restart: unless-stopped
